name: 'Acceptance Tests'
run-name: '${{ github.actor }} triggered a run on ${{ github.ref_name }}'
on:
  pull_request:
    branches:
      - dev
      - main
  # Uncomment for testing 
  push:
    branches:
      - auth-settings

jobs:
  run-acc-test-suite:
    name: 'Run Acceptance Test Suite'
    runs-on: ubuntu-latest
    environment: susanpolgar # Internal Cortex Cloud test instance
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          path: 'terraform-provider-cortexcloud'

      - name: 'Setup Go'
        uses: actions/setup-go@v5
        with:
          go-version-file: 'terraform-provider-cortexcloud/go.mod'
          cache: true
          cache-dependency-path: terraform-provider-cortexcloud/go.sum
    
      - name: 'Run Go Linter'
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
          working-directory: 'terraform-provider-cortexcloud'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.12.1'

      - name: Run Acceptance Tests
        working-directory: 'terraform-provider-cortexcloud'
        env:
          TF_ACC: 1
          CORTEX_API_URL: ${{ vars.CORTEX_API_URL }}
          CORTEX_API_KEY: ${{ secrets.CORTEX_API_KEY }}
          CORTEX_API_KEY_ID: ${{ secrets.CORTEX_API_KEY_ID }}
        run: go test -v -cover -race -mod=vendor $(go list ./... | grep -v /vendor/)
