name: 'Go Linter'
run-name: '${{ github.actor }} triggered a run on ${{ github.ref_name }}'
on: [push]
  #pull_request:
  #  branches:
  #    - dev
  #    - main
  ## Uncomment for testing 
  #push:
  #  branches:
  #    - auth-settings

jobs:
  run-acc-test-suite:
    name: 'Run Acceptance Test Suite'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          path: 'terraform-provider-cortexcloud'

      - name: 'Setup Go'
        uses: actions/setup-go@v5
        with:
          go-version-file: 'terraform-provider-cortexcloud/go.mod'
          cache: true
          cache-dependency-path: terraform-provider-cortexcloud/go.sum
    
      - name: 'Run Go Linter'
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
          working-directory: 'terraform-provider-cortexcloud'
